package com.afan.dbmgr.config;

public interface DBErrCode {

	//找不到定义的列
	int ERR_COLUMN_NONE = 600;
	//事务
	int ERR_TRANSACTION = 601;
	//提交
	int ERR_COMMIT = 602;
	//回滚
	int ERR_ROLLBACK = 603;
	int ERR_CONN_NULL = 604;
	int ERR_PREPARECALL = 605;
	int ERR_PROXOOL_INIT = 606;
	int ERR_CONNECT_INIT = 607;
	int ERR_SAVE_POINT = 608;
	int ERR_RELEASE_SAVE_POINT = 609;
	int ERR_CONNECT_ALIA = 616;
	int ERR_CONNECT_WAIT = 617;
	
	int ERR_SET_INT = 610;
	int ERR_SET_LONG = 611;
	int ERR_SET_DOUBLE = 612;
	int ERR_SET_STRING = 613;
	int ERR_SET_OBJECT = 614;
	int ERR_SET_PARAM = 615;
	
	//default
	int ERR_MGR_INIT = 620;
	int ERR_MGR_PREPARE = 621;
	int ERR_MGR_PREPARE_SQL_VALUE = 622;
	int ERR_MGR_BATCH = 623;
	int ERR_MGR_BATCH_SQL = 624;
	int ERR_MGR_BATCH_VALUE = 625;
	int ERR_MGR_EXEC_QUERY = 626;
	int ERR_MGR_EXEC_UPDATE = 627;
	int ERR_MGR_EXEC_BATCH = 628;
	int ERR_MGR_PREPARE_SQL = 629;
	int ERR_MGR_EXEC_QUERY_SQL = 630;
	int ERR_MGR_EXEC_UPDATE_SQL = 631;
	int ERR_MGR_LAST_INSERT_ID = 632;
	int ERR_MGR_EXISTQUERY = 633;
	int ERR_MGR_AND_LAST_INSERT_ID = 634;
	int ERR_MGR_UN_SUPPORT = 635;
	int ERR_MGR_NO_HANDLER = 636;
	
	//wrapper
	int ERR_WMGR_PREPARE_SQL = 640;
	int ERR_WMGR_PREPARE_SQL_VALUE = 641;
	int ERR_WMGR_QUERY = 642;
	int ERR_WMGR_UPDATE = 643;
	int ERR_WMGR_EXISTQUERY = 644;
	int ERR_WMGR_PARAM = 645;
	int ERR_WMGR_SET_PARAM = 646;
	int ERR_BATCH_PARAM_NULL = 647;
	
	//wrapperStatemet
	int ERR_WSTAT_PARSE_SQL = 650;
	int ERR_WSTAT_PARSE_SQL_SALVE = 651;
	int ERR_WSTAT_CLEAR_PARAM = 652;
	int ERR_WSTAT_GENERATED_KEY = 653;
	int ERR_WSTAT_BATCH = 654;
	int ERR_WSTAT_EXEC_QUERY = 655;
	int ERR_WSTAT_EXEC_UPDATE = 656;
	int ERR_WSTAT_EXEC_BATCH = 657;
	int ERR_WSTAT_COLUMN_EXPRESSION = 658;
	int ERR_WSTAT_SET_PARAM = 659;
	
	//wrapperResult
	int ERR_WRESULT_INIT = 660;
	int ERR_WRESULT_EXEC = 661;
	int ERR_WRESULT_AUTOLOAD = 662;
	int ERR_WRESULT_SETMETHOD = 663;
	int ERR_WRESULT_INVOKESET = 664;
	int ERR_WRESULT_SET = 665;
	
	int ERR_SQL_INSERT = 670;
	int ERR_SQL_UPDATE = 671;
	int ERR_SQL_DELETE = 672;
	int ERR_SQL_SELECT = 673;
	int ERR_SQL_NOPRIMARY = 674;
	
	int ERR_SYNTAX_ERROR = 700;
	int ERR_COLUMN_NON_EXIST = 701;
	
}
